/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.dsd.simulador.trafego.view;

import com.mycompany.dsd.simulador.trafego.controller.Simulacao;
import com.mycompany.dsd.simulador.trafego.model.Celula;
import com.mycompany.dsd.simulador.trafego.model.Malha;
import com.mycompany.dsd.simulador.trafego.model.TipoCelula;
import com.mycompany.dsd.simulador.trafego.model.Veiculo;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.util.EnumMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.Timer;

/**
 *
 * @author gitir
 */
public class MalhaPanel extends javax.swing.JPanel {

    private final Malha malha;
    private final Simulacao simulacao;
    private final int cellSize = 30;

    private final Map<TipoCelula, Image> imagensSetas;

    /**
     * Creates new form MalhaPanel
     */
    public MalhaPanel(Malha malha, Simulacao simulacao) {
        this.malha = malha;
        this.simulacao = simulacao;
        this.imagensSetas = new EnumMap<>(TipoCelula.class);

        carregarImagens();

        new Timer(200, e -> repaint()).start();
    }

    /**
     * Carrega as imagens das setas do classpath para o mapa.
     */
    private void carregarImagens() {
        try {
            imagensSetas.put(TipoCelula.ESTRADA_CIMA, ImageIO.read(getClass().getResource("/imagens/setaCima.png")));
            imagensSetas.put(TipoCelula.ESTRADA_BAIXO, ImageIO.read(getClass().getResource("/imagens/setaBaixo.png")));
            imagensSetas.put(TipoCelula.ESTRADA_DIREITA, ImageIO.read(getClass().getResource("/imagens/setaDireita.png")));
            imagensSetas.put(TipoCelula.ESTRADA_ESQUERDA, ImageIO.read(getClass().getResource("/imagens/setaEsquerda.png")));
        } catch (IOException e) {
            System.err.println("Erro ao carregar imagens das setas.");
            e.printStackTrace();
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        for (int i = 0; i < malha.getLinhas(); i++) {
            for (int j = 0; j < malha.getColunas(); j++) {
                Celula cel = malha.getCelula(i, j);
                TipoCelula tipo = cel.getTipo();

                g.setColor(tipo == TipoCelula.VAZIO ? Color.LIGHT_GRAY : Color.WHITE);
                g.fillRect(j * cellSize, i * cellSize, cellSize, cellSize);

                if (imagensSetas.containsKey(tipo)) {
                    g.drawImage(imagensSetas.get(tipo), j * cellSize, i * cellSize, cellSize, cellSize, null);
                }

                g.setColor(Color.GRAY);
                g.drawRect(j * cellSize, i * cellSize, cellSize, cellSize);
            }
        }

        for (Veiculo v : simulacao.getVeiculos()) {
            if (v.isAtivo()) {
                g.setColor(v.getCor());
                g.fillOval(v.getColuna() * cellSize + 5, v.getLinha() * cellSize + 5,
                        cellSize - 10, cellSize - 10);
            }
        }
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(malha.getColunas() * cellSize, malha.getLinhas() * cellSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}